# Generated by Django 3.2.3 on 2021-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creditor_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=5)),
                ('mobile', models.IntegerField()),
                ('contactpersonname', models.CharField(max_length=40)),
                ('contactpersonmobile', models.IntegerField()),
                ('companyname', models.CharField(max_length=30)),
                ('homeno', models.IntegerField()),
                ('street', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('gstno', models.IntegerField()),
                ('pendingbalance', models.IntegerField()),
                ('creationdate', models.DateTimeField()),
            ],
        ),
    ]
