# Generated by Django 3.2.3 on 2021-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor_master',
            name='officeno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditor_master',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
