# Generated by Django 3.2.3 on 2021-06-25 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0002_auto_20210625_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor_master',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'Phone numer must be of 10 digit')]),
        ),
        migrations.AlterField(
            model_name='creditor_master',
            name='officeno',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7, 'Telephone numer must be of 10 digit')]),
        ),
    ]
