# Generated by Django 3.2.3 on 2021-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
