# Generated by Django 3.2.3 on 2021-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_shifttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shifttime',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Night', 'Night')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workinghours',
            field=models.IntegerField(),
        ),
    ]
