# Generated by Django 3.2.3 on 2021-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210621_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reference',
            field=models.CharField(max_length=50),
        ),
    ]
