# Generated by Django 3.2.3 on 2021-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tank_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('petrolbefore', models.FloatField()),
                ('dieselbefore', models.FloatField()),
                ('petrolafter', models.FloatField()),
                ('dieselafter', models.FloatField()),
                ('lostpetrol', models.FloatField()),
                ('lostdiesel', models.FloatField()),
                ('lostpetrolprice', models.FloatField()),
                ('lostdieselprice', models.FloatField()),
            ],
        ),
    ]
